system:
  develop_mode: false
  log_path: ./logs/log
  shutdown_timeout: 60

database:
  host: ck_db
  port: 5432
  username: omid
  password: omid121
  db_name: agahi-plus-plus_db
  max_idle_connection: 5
  max_open_connection: 5
  max_life_time: 60

http:
  host: 0.0.0.0
  port: 8000

divar:
  api:
    get_posts: https://open-api.divar.ir/v1/open-platform/finder/user-posts
    get_post: https://open-api.divar.ir/v1/open-platform/finder/post/{{token}}
    edit_post: https://open-api.divar.ir/v1/open-platform/post/{{token}}
    delete_widget: https://open-api.divar.ir/v1/open-platform/add-ons/post/{{post_token}}
    addons: https://open-api.divar.ir/v2/open-platform/addons/post/{{post_token}}

  apartment:
    client_id: solar-lead-lord
    client_secret: 52f0e652ba2d5d9437d666ebd922eb8573a3758bcab7a9a405b5376213a0bd63a927330d9af3e65c3fb3c22422bda16a3d81b211561e842be571b620984c38a7
    api_key: eyJhbGciOiJSUzI1NiIsImtpZCI6InByaXZhdGVfa2V5XzIiLCJ0eXAiOiJKV1QifQ.eyJhcHBfc2x1ZyI6InNvbGFyLWxlYWQtbG9yZCIsImF1ZCI6InNlcnZpY2Vwcm92aWRlcnMiLCJleHAiOjE3NjIzNDIzNTMsImp0aSI6IjJlNWIwNTlhLThiMTUtMTFmMC1hZWRhLTRhNmU5Y2EyZDk3OSIsImlhdCI6MTc1NzE1ODM1MywiaXNzIjoiZGl2YXIiLCJzdWIiOiJhcGlrZXkifQ.Lkte6hMD2BmotZ2HHBaoPmPsOkBBXUamxn6POfbapsHY_KBAGUH9Aj9d9Qf2qv3rzyIWZb9UmWiEn8MgK4e80RlfG2k0hCf3sxotiQfZDFPm2Bol-ofVwKJC9iZNUQ_ooT3MI1XClpGRYZU_W4dJAQa0xfBb2Kxx9CS09pe2MNqpG-aDH6qiyyUZz5zJu1BwdfsOE3NfeKfmaF3m6GUAKyy_49QkX6C7SJJit0dLsxYm5IMsrOilWS-WFMhc2TvMgBKtqooi6p52sTzwIal4yHv2saYYq1iduR64SrDc4OZl8vlBEzPlOTT1iIPGe57YxePjeG6IKTUNUXMZtA3EnA
    redirect_uri: https://api.divarinow.ir/v1/user/oauth/apartment
    image: 368c02f2-340b-4602-83a5-efc2b3d2407b.jpg
    scopes: USER_PHONE%20POST_ADDON_CREATE.

    oauth:
      base_url: https://oauth.divar.ir/oauth2/auth?response_type=%s&client_id=%s&redirect_uri=%s&scope=%s&state=%s
      response_type: code

    oauth_token:
      base_url: https://oauth.divar.ir/oauth2/token
      grant_type: authorization_code

    oauth_phone_number:
      base_url: https://open-api.divar.ir/v1/open-platform/users

app:
  salt: _E[*.61P.wA;-M>sS>Gb?@ZVd&>zp"C=A=R=p+.=K0d7CQ1R\WX;froI?wY![io`7Hk`<p=:xlK{nA<T[22H,ziR0Nv-BqweuMca+cZ1gR&D<J[6_s<,ko[Yh!aooK~C
  inquiry_cost: 150000

  front_end_login_redirect: https://divarinow.ir/%s?pn=%s&t=%s&tt=%s
  front_end_purchase_redirect: https://divarinow.ir/payment?status=%d&ref_id=%s
  front_end_access_denied_redirect: https://divarinow.ir/request?state=%s&service=%s
  front_end_entry_redirect: https://divarinow.ir/entry

  llm_api_key: aa-JDpuqsYctmaNiypjpigyO1x45xn1EgfXB8hHO73T0QyGg5Zw
  llm_url: https://api.avalapis.ir/v1

  hash:
    salt: cvbn68eqeqwy
    alphabet: abcdefghijklmnopqrstuvwxyz123458760
    min_length: 6

  test: false

  kenar_redirect_base_url: https://divarinow.ir/kenar?code=%s&ref=%s
  kenar_divar_button: https://api.divarinow.ir/v1/profile/kenar/

jwt:
  secret: ;3A4caF_kc7|nB]RZvYk7<'`2(}#sEEi?upq&miG&RdxSHF3P)l1|f6$(BQK"[lr1219EbkZ{RRo|ci3<UW~M9p!L"[4|Q7cRr_$
  expire_hour: 48

zarinpal:
  merchant_id: 670ce05f-f854-4c72-8ad9-5a565c711217
  callback_url: https://api.divarinow.ir/v1/payment/verify?user_id=%d&amount=%d&id=%d&service=%s
  sandbox: false

yektanet:
  front_redirect_url: https://divarinow.ir/user/posts?access_token=%s&service=%s
  apartment:
    redirect_url: https://api.divarinow.ir/v1/user/ads/oauth/apartment
    client_id: divarinow-general
    response_type: code